body:
  - type: markdown
    attributes:
      value: |
        Welcome to networka discussions! 
        
        Please choose the appropriate category for your discussion:
        
        - **General** - General questions and discussions about networka
        - **Ideas** - Share ideas for new features or improvements
        - **Q&A** - Ask and answer questions about using networka
        - **Show and tell** - Share what you've built with networka
        - **Announcements** - Project announcements (maintainer only)
