# Vendor Platform Configurations for Sequence Management
# This file defines how vendor-specific sequences are discovered and loaded

vendor_platforms:
  mikrotik_routeros:
    description: "MikroTik RouterOS devices"
    sequence_path: "sequences/mikrotik_routeros"
    default_files: ["common.yml"]

  cisco_iosxe:
    description: "Cisco IOS-XE devices"
    sequence_path: "sequences/cisco_iosxe"
    default_files: ["common.yml"]

  cisco_nxos:
    description: "Cisco NX-OS devices"
    sequence_path: "sequences/cisco_nxos"
    default_files: ["common.yml"]

  juniper_junos:
    description: "Juniper JunOS devices"
    sequence_path: "sequences/juniper_junos"
    default_files: ["common.yml"]

  arista_eos:
    description: "Arista EOS devices"
    sequence_path: "sequences/arista_eos"
    default_files: ["common.yml"]

# Global sequences that apply to all vendors (optional)
sequences: {}
