general:
  default_transport_type: scrapli
  port: 22
  timeout: 30

devices:
  srl1:
    host: 172.20.20.2
    device_type: nokia_srlinux
    description: Nokia SR Linux containerlab device
    tags:
      - nokia
      - srlinux
      - lab
